const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swaggerDoc.json'
const endpointsFiles = ['./routes/user.routes', './routes/project.routes', './routes/contactMe.route','./routes/resume.routes']
const doc = {
  info: {
    version: "1.0.0",
    title: "My API",
    description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
  },
  host: "localhost:2500",
  basePath: "/",
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
//   tags: [{
//     "name": "",
//     "description": "Endpoints"
//   }],
  securityDefinitions: {
    api_key: {
      type: "apiKey",
      name: "api_key",
      in: "header"
    },
  },
}

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require('./app.js')
})