const swaggerAutogen = require('swagger-autogen')();

const outputFile = './swaggerDoc.json';
const endpointsFiles = ['./routes/user.routes', './routes/project.routes', './routes/contactMe.route','./routes/resume.routes'];

// Define the default configuration
const defaultDoc = {
  info: {
    version: "1.0.0",
    title: "My API",
    description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
  },
  host: process.env.NODE_ENV === 'production' ? "https://my-portfolio-dgjg.onrender.com" : "localhost:2500",
  basePath: "/",
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  securityDefinitions: {
    api_key: {
      type: "apiKey",
      name: "api_key",
      in: "header"
    },
  },
};

// Generate Swagger documentation
swaggerAutogen(outputFile, endpointsFiles, defaultDoc).then(() => {
  require('./app.js');
});